---
docker_options: "--selinux-enabled -H tcp://localhost:2375"
docker_host: "tcp://localhost:2375"
docker_registry_certificates: "/etc/docker/certs.d/registry.jufis.net:443"
docker_registry_path: "registry.jufis.net:443"
docker_client_certificates: "/home/jufis/.docker"
