---
expose_port: "8080"
docker_application_name: "docker-rest-server"
docker_host: "tcp://localhost:2376"
git_tag: "TAG_SERVER_SECURITY_PROFILE_master"
docker_repository: "ci"
docker_registry_name: "registry.jufis.net"
docker_registry_ip: "192.168.1.7"
docker_registry_location: "registry.jufis.net:443"
docker_server: "docker.jufis.net"
